### PR TITLE
Changes the parse_locations function in /models/geoname.py 

### PR DESCRIPTION
**Pull request by ghost**
1. ### Sets default lang to "en".
   
   Geonames database has duplicates based on lang, besides current DB has "iata" set as a lang for iata         city codes. 
   e.g. GOA is iata code for Genoa, and shows up in search if lang is not set.
2. ### Changes parse_locations function to calculate distance between two tokens and sorts by shortest distance.
   
   Takes db search results for each token provided by user, calculates the geographical distance             between the two tokens (places) by a function called `distance`, which takes latitude and longitude as parameters and returns distance in kms. The relatedness of tokens is inversely proportional to the geographical distance between them.

### CODE REVIEW

**Comment by sindhus** [comment]
I pulled your branch locally and tried to test out the commit "Changes parse_location function for parsing single token" with the URL `http://localhost:8070/1/geo/parse_locations?q=goa` and I got:

```
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sindhus/hasgeek/coaster/coaster/views.py", line 189, in decorated_function
    return f(**kw)
  File "/Users/sindhus/hasgeek/hascore/hascore/views/geoname.py", line 46, in geo_parse_location
    result = GeoName.parse_locations(q, special, lang, bias)
  File "/Users/sindhus/hasgeek/hascore/hascore/models/geoname.py", line 364, in parse_locations
    accepted.sort(
UnboundLocalError: local variable 'accepted' referenced before assignment
```

It's a good idea to test your code before you send a PR and include "Before" (Old code's results) and "After" (New code's improved results") in the PR description.

**Comment by rautarchana9** [comment]
Thank you for feedback. But since your server is not parsing token "goa" itself. I assume your DB configuration is not correct. However I have made a new commit which will take care of exceptions.

**Comment by jace** [comment]
@rautarchana9 `UnboundLocalError` has nothing to do with the database. It's a programming error.

**Comment by rautarchana9** [comment]
True Kiran, I didn't handle the exception I agree. What I meant was since token "goa" should find match in DB, this error should not come.

**Pull request closed without merging**
